---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: httpd-deployment
    labels:
       type: webserver
spec:
   selector: 
      matchLabels:
           type: webserver
           author: praneeth
   template:
      metadata:
         name: httpd-pod
         labels:
            type: webserver
            author: praneeth
      spec:
          containers:
             - name: myhttpd
               image: httpd
               ports:
                   - containerPort: 80
                     hostPort: 8080


                       
