---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: jenkins-deployment
spec:
   replicas: 2
   selector:
       matchLabels:
         author: kore
         type: ci-cd
   template:
      metadata:
           name: jenkins-pod
           labels:
             author: kore
             type: ci-cd
      spec:
          containers:
              - name: jenkinscon
                image: jenkins/jenkins
---
apiVersion: v1
kind: Service
metadata:
   name: loadbalancer
spec:
   type: LoadBalancer
   ports:
     - targetPort: 8080
       port: 88
       nodePort: 31000
   selector:
      author: kore
      type: ci-cd     


