---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
   replicas: 2
   selector:
     matchLabels:
         type: mytype
   template:
       metadata:
           name: myhttpd-pod
           labels:
               type: mytype
       spec:
          containers:
             - name: myhttpd
               image: httpd
               ports:
                    - containerPort: 80
                      hostPort: 8888
...                        
