---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxy
spec:
  replicas: 4
  selector:
     matchLabels:
        author: praneeth
        type: proxy
  template: 
     metadata:
       name: nginx-pod
       labels: 
          author: praneeth
          type: proxy
     spec:
        containers:
           - name: mynginx
             image: nginx
             ports:
               - containerPort: 80
                 hostPort: 8080
...                  
