---
apiVersion: v1
kind: Pod
metadata:
  name: mynginx-pod
  labels:
    author: sree
spec:
   containers:
          - name: mynginx
            image: nginx
---
apiVersion: v1
kind: Service
metadata:
   name: nodeport-service
spec:
   type: NodePort
   ports:
      - targetPort: 80
        port: 90
        nodePort: 32567
   selector:
     author: sree     
