---
apiVersion: v1
kind: Pod
metadata: 
   name: mywp
   namespace: mynamespace
   labels:
     type: proxy
spec:
   containers:
      - name: mywp
        image: wordpress
        ports:
          - containerPort: 80
            hostPort: 1111
...              
