---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: praneeth
spec:
  containers:
     - name: mynginx
       image: nginx
       ports:
         - containerPort: 80
           hostPort: 8080
     - name: myjenkins
       image: jenkins/jenkins
       ports:
          - containerPort: 8080
            hostPort: 8888
...              
