---
apiVersion: v1
kind: ReplicationController
metadata:
   name: httpd-rc
   labels:
     author: praneeth
spec:
  replicas: 2
  template:
    metadata:
      name: httpd-pod
      labels:
         type: appserver
    spec: 
      containers:
           - name: myhttpd
             image: httpd
             ports:
               - containerPort: 80
                 hostPort: 8080
...                   
