---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rs
  labels:
    author: praneeth
spec:
   replicas: 2
   selector:
      matchLabels:
          author: praneeth
   template:
       metadata:
          name: tomee-pod
          labels:
              author: praneeth
       spec:
          containers:
              - name: mytomcat
                image: tomee
                ports:
                   - containerPort: 80
                     hostPort: 8080
...                       
